
(function(){
  const SAVE_KEY = 'loa_upgrade_batch27';
  const XP_PER_LEVEL = [0,0,3,7,12,18,25,33,42,52,63,75,88,102,117,133,150,168,187,207,228];
  let G = null;

  const $ = id=>document.getElementById(id);
  const pick=(arr,n)=>arr&&arr.length?arr[n%arr.length]:'';
  const rand=n=>Math.floor(Math.random()*n);
  const currentStage=l=>(window.STAGES||[]).find(s=>l>=s.levelMin&&l<=s.levelMax)||(window.STAGES||[])[0];
  const getArchetype=id=>(window.ARCHETYPES||[]).find(a=>a.id===id);
  const getBackground=(arch,bgId)=>((window.BACKGROUNDS||{})[arch]||[]).find(b=>b.id===bgId);
  const getLocality=id=>(window.KEY_LOCALITIES||{})[id];
  const routeSignature=()=>window.BACKGROUND_ROUTE_SIGNATURES[G.backgroundId];
  const routeAtlasFor=sig=>(window.ROUTE_ATLAS||{})[sig.stage2Vector]||{style:'unclassified route',risk:'unknown',note:'The road has not yet been stabilized in the atlas.'};
  const destinationStage2Content=dest=>(window.STAGE2_DESTINATION_CONTENT||{})[dest]||[];
  const familyTitleForStage2=sig=>((window.FAMILY_OBJECTIVES||{})[sig.stage2Family]||{}).title||'Adjacent Pressure';
  const storage=()=>{ try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'{}');}catch{return{};} };
  const persist=()=>{ const all=storage(); all[G.passcode]=G; localStorage.setItem(SAVE_KEY, JSON.stringify(all)); };

  function defaultState(){
    const defaultBgId = 'warrior_civic';
    const startingLocation = (window.getStartingLocality && window.getStartingLocality(defaultBgId)) || 'shelkopolis';
    return {
      name:'', passcode:'', archetype:'warrior', backgroundId:defaultBgId, level:1, xp:0, renown:0,
      hp:22, maxHp:22, gold:20, stage:1, stageLabel:STAGES[0].label, currentObjective:'', dayCount:1, timeIndex:0,
      age:'24', presentation:'Male', lineage:'Human', lifeOverview:'',
      location:startingLocation, currentSafeZone:'Roadwarden Annex Ward', routeHistory:[], safeZoneHistory:[],
      journalRecords:[], notices:[], legends:[], quests:[], factions:{}, morality:0, order:0,
      skills:{combat:2,survival:1,persuasion:1,lore:1,stealth:1,craft:1}, companions:[], recruitableSeen:{},
      wounds:[], fatigue:0, deathCount:0, stage5Dead:false, rescueLog:[], trainingDisadvantage:0,
      worldClocks:{pressure:0,rival:0,omens:0}, stageProgress:{1:0,2:0,3:0,4:0,5:0},
      routeScoutLog:[], keyMoments:[], currentThreat:null, encounter:null, lastResult:'Your ledger waits for its first truth.',
      buildAudit: window.BUILD_VERIFICATION, familyMilestones:{stage3:0,stage4:0,stage5:0}, familyEdges:[], finalBreak:false,
      telemetry:{turns:0,actions:0,travels:0,scouts:0,encounters:0,wins:0,rescues:0,services:0},
      inventory:[], equipment:{}, serviceLog:[], signals:{}, settlementSecrets:{}, stage2DestinationsSeen:{}
    };
  }
  function addJournal(category,text,dedupeKey){ if(dedupeKey && G.journalRecords.some(r=>r.dedupeKey===dedupeKey)) return; G.journalRecords.unshift({day:G.dayCount,locality:G.location,category,text,dedupeKey}); G.journalRecords=G.journalRecords.slice(0,120); }
  function addNotice(text){ G.notices.unshift(`Day ${G.dayCount}: ${text}`); G.notices=G.notices.slice(0,50); }
  function addQuest(id,title,status='Active'){ const q=G.quests.find(q=>q.id===id); if(q){ q.status=status; return; } G.quests.push({id,title,status}); }
  function markMoment(text){ G.keyMoments.unshift(`Day ${G.dayCount}: ${text}`); G.keyMoments=G.keyMoments.slice(0,25); }
  function advanceTime(t=1){ for(let i=0;i<t;i++){ G.timeIndex=(G.timeIndex+1)%5; if(G.timeIndex===0) G.dayCount+=1; G.worldClocks.pressure++; if(G.stage>=2) G.worldClocks.rival++; if(G.stage>=4) G.worldClocks.omens++; if(G.trainingDisadvantage>0) G.trainingDisadvantage--; } }
  function gainXp(n,why=''){ G.xp+=n; while(G.level<20 && G.xp>=XP_PER_LEVEL[G.level+1]){ G.level++; G.maxHp += G.stage>=4?4:3; G.hp=Math.min(G.maxHp,G.hp+4); G.renown+=2; addNotice(`Level ${G.level} reached${why?` — ${why}`:''}.`);} updateStage(); }
  function updateStage(){ const st=currentStage(G.level); G.stage=st.id; G.stageLabel=st.label; }
  function chooseThreat(){ const loc=getLocality(G.location); return {hazard:pick(loc.hazards,G.dayCount+G.stage+G.worldClocks.pressure), creature:pick(loc.creatures,G.dayCount+G.stage+G.worldClocks.rival)}; }
  function setThreat(){ G.currentThreat = chooseThreat(); }
  function currentNamedPlacements(location){ return (window.NPC_PLACEMENTS||{})[location] || []; }
  function buildAuditText(){ const b=window.BUILD_VERIFICATION||{}; return `${b.archetypeCount} archetypes · ${b.backgroundCount} backgrounds · ${b.routeSignatureCount} routes · ${b.localityProjectionCount} localities`; }
  function gearBonus(key){ let bonus=0; Object.values(G.equipment||{}).forEach(item=>{ if(item && item.bonus && item.bonus[key]) bonus += item.bonus[key]; }); return bonus; }
  function currentEdgeBonus(action){ return (G.familyEdges||[]).reduce((sum,e)=>sum + (e.action===action?e.bonus:0), 0); }
  function familyEdgesText(){ return (G.familyEdges||[]).map(e=>`${e.label} (+${e.bonus} ${e.action})`).join(' · ') || 'None'; }
  function updateSignals(){
    const group = getArchetype(G.archetype).group;
    if(group==='combat') G.signals={primary:`Stance ${2+gearBonus('brace')}`,secondary:`Guard ${1+gearBonus('guard')}`,tertiary:`Armor ${Object.keys(G.equipment).length}`};
    else if(group==='magic') G.signals={primary:`Arcana ${G.skills.lore+gearBonus('arcana')}`,secondary:`Ward ${1+gearBonus('ward')}`,tertiary:`Reagents ${G.inventory.filter(i=>/reagent|chalk|focus/i.test(i.name)).length}`};
    else if(group==='stealth') G.signals={primary:`Concealment ${G.skills.stealth+gearBonus('concealment')}`,secondary:`Suspicion ${Math.max(0,G.worldClocks.rival-1)}`,tertiary:`Tools ${G.inventory.filter(i=>/tool|wrap|vial/i.test(i.name)).length}`};
    else G.signals={primary:`Kits ${1+gearBonus('kits')}`,secondary:`Resolve ${1+G.companions.length}`,tertiary:`Coordination ${gearBonus('coordination')}`};
  }
  function maybeUnlockFamilyEdge(stage){ const sig=routeSignature(); const fam=sig[`stage${stage}Family`]; const reward=(window.FAMILY_EDGE_REWARDS||{})[fam] && window.FAMILY_EDGE_REWARDS[fam][`stage${stage}`]; if(!reward)return; const key=`${fam}-stage${stage}`; G.familyEdges=G.familyEdges||[]; if(G.familyEdges.some(e=>e.key===key)) return; G.familyEdges.push({key,family:fam,stage,...reward}); addNotice(`Family edge unlocked: ${reward.label}.`); markMoment(`Unlocked ${reward.label}`); }
  function stage1Objective(){ const bg=getBackground(G.archetype,G.backgroundId); return bg?bg.firstObjective:'Read the locality and find the hidden hand.'; }
  function stage2Objective(){ const sig=routeSignature(); const atlas=routeAtlasFor(sig); const adj=(window.ADJACENCY[G.location]||[]).map(id=>getLocality(id)?.name).filter(Boolean); return `Push beyond ${getLocality(sig.originLocality).name} along ${window.ROUTE_NAMES[sig.stage2Vector]} (${atlas.style}) into ${adj.slice(0,2).join(' and ')||'adjacent ground'} and decide who controls the widening pressure of ${familyTitleForStage2(sig)}.`; }
  function stage3Objective(){ const fam=window.FAMILY_OBJECTIVES[routeSignature().stage3Family]; return `${fam.stage3} Milestones: ${G.familyMilestones.stage3}/3.`; }
  function stage4Objective(){ const fam=window.FAMILY_OBJECTIVES[routeSignature().stage4Family]; return `${fam.stage4} Milestones: ${G.familyMilestones.stage4}/3.`; }
  function stage5Objective(){ const fam=window.FAMILY_OBJECTIVES[routeSignature().stage5Family]; return G.finalBreak?`Final break committed in ${fam.title}. Face the endgame.`:`${fam.stage5} Milestones: ${G.familyMilestones.stage5}/4.`; }
  function setObjective(){ G.currentObjective = G.stage===1?stage1Objective():G.stage===2?stage2Objective():G.stage===3?stage3Objective():G.stage===4?stage4Objective():stage5Objective(); }
  function applySuccess(stage, mode, skill, xp, text){ G.stageProgress[stage]+=1; gainXp(xp, `${mode} pressure`); if(stage>=3){ G.familyMilestones[`stage${stage}`]=(G.familyMilestones[`stage${stage}`]||0)+1; if(G.familyMilestones[`stage${stage}`]===2) maybeUnlockFamilyEdge(stage); } G.lastResult=text; if(stage===5 && G.familyMilestones.stage5>=4 && !G.finalBreak){ G.finalBreak=true; maybeUnlockFamilyEdge(5); addNotice('A final break becomes possible.'); } }
  function objectiveWebChoices(stage){ const verbs=[['Question a person at the center of the pressure','person','persuasion'],['Search the place where the pressure shows physically','place','lore'],['Pull records and compare what should not align','records','lore'],['Work the quiet edge and move unseen','stealth','stealth'],['Force an opening in the line','force','combat'],['Use ritual or procedure to open a blocked answer','ritual','craft'],['Trace the route itself for what it carries','route','survival']]; return verbs.map(([label,mode,skill],i)=>({label,tags:['Objective',mode],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; const comp=window.companionBonus?companionBonus(G,skill):0; const total = 1+rand(20)+(G.skills[skill]||0)+comp+Math.floor(G.level/3)+currentEdgeBonus(mode); const target=10+stage*2+i%2; const success=total>=target; addJournal('field-note',`${label} in ${getLocality(G.location).name}.`,`${G.backgroundId}-${stage}-${mode}-${G.dayCount}`); if(success){ applySuccess(stage,mode,skill,stage,`${label} pays off. The route opens a little wider, and the shape of the pressure becomes harder to hide.`); } else { G.lastResult=`${label} fails to settle the matter. The opposition keeps the initiative.`; G.worldClocks.rival+=1; if(rand(3)===0) startThreatEncounter('standard'); } maybeStageAdvance(); }})); }
  function classIdentityChoice(){ const a=getArchetype(G.archetype); const group=a.group; if(group==='combat') return {label:'Set a hard stance and test the line physically',tags:['Class','Combat'],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; G.skills.combat+=1; gainXp(2,'martial posture'); G.lastResult='Weight, footing, and guard tell more truth than anyone intended to show.'; maybeStageAdvance(); }}; if(group==='magic') return {label:'Read residue, wards, and unstable traces',tags:['Class','Magic'],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; G.skills.lore+=1; gainXp(2,'arcane read'); G.lastResult='Charged residue and ward strain make the hidden pattern easier to follow.'; maybeStageAdvance(); }}; if(group==='stealth') return {label:'Work the unnoticed angle and read who is watching whom',tags:['Class','Stealth'],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; G.skills.stealth+=1; gainXp(2,'concealment read'); G.lastResult='Sightlines and timing windows expose the pressure without a public clash.'; maybeStageAdvance(); }}; return {label:'Stabilize the weak point before it breaks wider',tags:['Class','Support'],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; G.skills.craft+=1; gainXp(2,'support discipline'); G.lastResult='Useful hands, clean tools, and practical discipline turn panic into leverage.'; maybeStageAdvance(); }}; }

  function stage2ClassIdentityChoice(){
    const a=getArchetype(G.archetype); const sig=routeSignature();
    if(a.group==='combat') return {label:'Take the lead physically on the widening route',tags:['Class','Adjacent','Combat'],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; G.skills.combat+=1; gainXp(2,'route command'); G.lastResult=`The widening route starts answering to visible force, disciplined posture, and the threat of immediate correction.`; G.routeScoutLog.unshift(`${G.location} / ${window.ROUTE_NAMES[sig.stage2Vector]} / martial command`); G.routeScoutLog=G.routeScoutLog.slice(0,20); maybeStageAdvance(); }};
    if(a.group==='magic') return {label:'Read wards, residue, and pressure seams on the widening route',tags:['Class','Adjacent','Magic'],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; G.skills.lore+=1; gainXp(2,'arcane widening'); G.lastResult=`The adjacent pressure gives up its magical seams once the route is read as a structure instead of a story.`; G.routeScoutLog.unshift(`${G.location} / ${window.ROUTE_NAMES[sig.stage2Vector]} / ward reading`); G.routeScoutLog=G.routeScoutLog.slice(0,20); maybeStageAdvance(); }};
    if(a.group==='stealth') return {label:'Work the widening edge through timing, concealment, and quiet access',tags:['Class','Adjacent','Stealth'],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; G.skills.stealth+=1; gainXp(2,'covert widening'); G.lastResult=`The adjacent route opens by way of blind corners, bad habits, and people who think nobody is counting them.`; G.routeScoutLog.unshift(`${G.location} / ${window.ROUTE_NAMES[sig.stage2Vector]} / covert edge`); G.routeScoutLog=G.routeScoutLog.slice(0,20); maybeStageAdvance(); }};
    return {label:'Stabilize the widening line before it becomes a regional problem',tags:['Class','Adjacent','Support'],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; G.skills.craft+=1; gainXp(2,'support widening'); G.lastResult=`The widening pressure becomes manageable once tools, kits, and disciplined help hit the right weak point.`; G.routeScoutLog.unshift(`${G.location} / ${window.ROUTE_NAMES[sig.stage2Vector]} / support triage`); G.routeScoutLog=G.routeScoutLog.slice(0,20); maybeStageAdvance(); }};
  }

  function stage1Choices(){ const bg=getBackground(G.archetype,G.backgroundId); const loc=getLocality(G.location); const recruit=window.recruitChoice?recruitChoice(G):null; const choices=[ {label:`Observe ${loc.name} through ${bg.theme}`,tags:['Safe'],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; gainXp(1,'careful observation'); G.stageProgress[1]++; addJournal('field-note',`Observed ${loc.name} through ${bg.theme}.`,`${bg.id}-observe`); G.lastResult=`A quieter read of ${loc.name} sharpens the first contradiction.`; maybeStageAdvance(); }}, classIdentityChoice(), ...objectiveWebChoices(1).slice(0,3), {label:'Test the current threat directly',tags:['Risky','Encounter'],fn(){ G.telemetry.actions++; startThreatEncounter('standard'); }}, {label:'Make camp and regroup',tags:['Camp'],fn(){ G.lastResult='The line pulls back into a safer rhythm.'; }} ]; if(recruit) choices.splice(3,0,recruit); return choices.slice(0,8); }
  function travelTo(dest){ const from=getLocality(G.location); const to=getLocality(dest); G.location=dest; G.currentSafeZone=to.safeZone; G.routeHistory.unshift(`${from.name} → ${to.name}`); G.routeHistory=G.routeHistory.slice(0,25); G.telemetry.travels++; advanceTime(1); addJournal('travel',`Moved from ${from.name} to ${to.name}.`,`${G.backgroundId}-travel-${from.id}-${to.id}-${G.dayCount}`); G.lastResult=`${to.name} takes the run into a more adjacent, less forgiving version of the same pressure.`; setThreat(); }
  function stage2Choices(){ const sig=routeSignature(); const atlas=routeAtlasFor(sig); 
    // Check for background-specific Stage II content first
    let bgStage2Content = (window.BACKGROUND_STAGE2_CONTENT||{})[G.backgroundId];
    const familyContent = !bgStage2Content ? (window.STAGE2_FAMILY_CONTENT[sig.stage2Vector]||[]) : [];
    const contentToUse = bgStage2Content || {choices: familyContent};
    const adj=(window.ADJACENCY[G.location]||[]);
    
    const bgChoices = (contentToUse.choices||[]).map((entry,idx)=>({label:entry.label,tags:['Adjacent',entry.mode,atlas.risk],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; const comp=window.companionBonus?companionBonus(G,entry.skill):0; const total=1+rand(20)+(G.skills[entry.skill]||0)+comp+Math.floor(G.level/3)+currentEdgeBonus(entry.mode); const target=12+idx; const success=total>=target; addJournal('adjacent-pressure',`${entry.label} on ${window.ROUTE_NAMES[sig.stage2Vector] || 'the route'}.`,`${G.backgroundId}-stage2-${entry.mode}-${idx}`); if(success){ G.routeScoutLog.unshift(`${G.location} / ${window.ROUTE_NAMES[sig.stage2Vector] || 'route'} / ${entry.mode}`); G.routeScoutLog=G.routeScoutLog.slice(0,20); applySuccess(2, entry.mode, entry.skill, 2, entry.success); } else { G.worldClocks.rival +=1; G.lastResult=entry.fail; if(rand(3)===0) startThreatEncounter('standard'); } maybeStageAdvance(); }}));
    const destinationChoices = adj.flatMap(dest=> destinationStage2Content(dest).slice(0,1).map((entry,idx)=>({label:`${getLocality(dest).name}: ${entry.label}`,tags:['Adjacent','Destination',entry.mode],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; const comp=window.companionBonus?companionBonus(G,entry.skill):0; const total=1+rand(20)+(G.skills[entry.skill]||0)+comp+Math.floor(G.level/3)+currentEdgeBonus(entry.mode); const target=13+idx; const success=total>=target; G.stage2DestinationsSeen[dest]=true; addJournal('regional-pressure',`${entry.label} in ${getLocality(dest).name}.`,`${G.backgroundId}-stage2-dest-${dest}-${idx}`); if(success){ G.routeScoutLog.unshift(`${G.location} / ${getLocality(dest).name} / ${entry.mode}`); G.routeScoutLog=G.routeScoutLog.slice(0,20); applySuccess(2, entry.mode, entry.skill, 2, entry.success); G.lastResult = entry.success; } else { G.worldClocks.rival +=1; G.lastResult = entry.fail; if(rand(4)===0) startThreatEncounter('standard'); } maybeStageAdvance(); }})));
    const travel = adj.map(dest=>({label:`Travel to ${getLocality(dest).name}`,tags:['Travel','Adjacent'],fn(){ travelTo(dest); G.stage2DestinationsSeen[dest]=true; }}));
    const scouting = adj.map(dest=>({label:`Scout ${getLocality(dest).name} via ${atlas.style}`,tags:['Travel','Scout',atlas.risk],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.scouts++; G.stage2DestinationsSeen[dest]=true; G.routeScoutLog.unshift(`${G.location} → ${dest} (${atlas.risk})`); G.routeScoutLog=G.routeScoutLog.slice(0,20); G.lastResult=`${getLocality(dest).name} comes into view through ${atlas.style}, and the risk reads as ${atlas.risk}.`; }}));
    const classRoute = stage2ClassIdentityChoice();
    return [
      ...bgChoices.slice(0,2),
      ...destinationChoices.slice(0,2),
      ...objectiveWebChoices(2).slice(0,1),
      classRoute,
      ...travel.slice(0,1),
      ...scouting.slice(0,1),
      {label:'Use the current safe zone for leverage',tags:['Camp','Leverage'],fn(){ advanceTime(1); G.telemetry.turns++; G.telemetry.actions++; gainXp(1,'safe zone leverage'); G.lastResult=`${G.currentSafeZone} provides enough shelter to force one useful concession.`; }},
      {label:'Call on a settlement service before pushing further',tags:['Service','Adjacent'],fn(){ G.lastResult='A return through the current settlement services sharpens the next move.'; }}
    ].slice(0,9);
  }
  function campChoices(state){
    const loc=getLocality(state.location);
    return [
      {label:`Rest at ${state.currentSafeZone} and recover`,tags:['Rest','HP'],fn(){ advanceTime(1); state.hp=Math.min(state.maxHp,state.hp+Math.max(3,Math.floor(state.maxHp*0.3))); state.fatigue=Math.max(0,state.fatigue-1); state.lastResult=`${state.currentSafeZone} steadies the body. The next move starts from a better place.`; addJournal('camp',`Rested at ${state.currentSafeZone}.`,`camp-rest-${state.dayCount}`); }},
      {label:`Review the journal and sharpen the approach`,tags:['Reflect','Lore'],fn(){ advanceTime(1); gainXp(1,'careful reflection'); state.lastResult=`The journal yields one pattern that was not visible in motion.`; addJournal('camp','Reviewed field notes and updated the approach.',`camp-reflect-${state.dayCount}`); }},
      {label:`Scout the immediate area around ${loc.name}`,tags:['Scout','Survival'],fn(){ advanceTime(1); state.telemetry.scouts++; state.skills.survival=(state.skills.survival||0)+1; const t=chooseThreat(); state.currentThreat=t; state.lastResult=`The perimeter of ${loc.name} gives up one useful detail about what is moving and what is holding still.`; }},
      {label:`Maintain equipment and prepare for the next push`,tags:['Craft','Prep'],fn(){ advanceTime(1); state.skills.craft=(state.skills.craft||0)+1; gainXp(1,'field maintenance'); state.lastResult=`Gear is clean, edges are sound, and the next move starts with better tools than the last one.`; }}
    ];
  }

  function beginEncounter(state, kind, name, tier){
    state.encounter={ kind, name:name||'unknown threat', tier:tier||'standard', round:1, started:state.dayCount, hp:kind==='creature'?(window.BESTIARY&&window.BESTIARY[name]?window.BESTIARY[name].hp:12):(window.HAZARDS&&window.HAZARDS[name]?window.HAZARDS[name].severity*4:8), maxHp:kind==='creature'?(window.BESTIARY&&window.BESTIARY[name]?window.BESTIARY[name].hp:12):(window.HAZARDS&&window.HAZARDS[name]?window.HAZARDS[name].severity*4:8) };
    const desc=kind==='creature'?(window.BESTIARY&&window.BESTIARY[name]?window.BESTIARY[name].text:'A threat emerges from the pressure.'):(window.HAZARDS&&window.HAZARDS[name]?window.HAZARDS[name].text:'A hazard breaks into the open.');
    state.lastResult=`${desc} The encounter demands an immediate answer.`;
  }

  function encounterChoices(state){
    const enc=state.encounter;
    if(!enc) return stage1Choices();
    const arch=getArchetype(state.archetype);
    const tierBonus=enc.tier==='elite'?3:enc.tier==='boss'?6:0;
    function resolve(skill,label,xpAmt,successText,failText){
      const roll=1+rand(20)+(state.skills[skill]||0)+Math.floor(state.level/3)+tierBonus;
      const target=enc.tier==='boss'?18:enc.tier==='elite'?15:12;
      const success=roll>=target;
      if(success){ gainXp(xpAmt,'encounter'); enc.hp=Math.max(0,enc.hp-Math.floor(state.level*1.5+5)); if(enc.hp<=0){ state.encounter=null; state.telemetry.wins++; state.gold+=rand(8)+3; state.lastResult=successText+` The threat is broken. (+${xpAmt} xp, gold gained)`; markMoment(`Defeated ${enc.name} at ${getLocality(state.location).name}`); } else { state.lastResult=successText+` The threat weakens but holds.`; } } else { const dmg=Math.max(1,rand(6)+enc.tier==='boss'?6:enc.tier==='elite'?4:2); state.hp=Math.max(0,state.hp-dmg); state.lastResult=failText+` You take ${dmg} damage (HP: ${state.hp}/${state.maxHp}).`; enc.round++; }
    }
    const choices=[
      {label:`Press forward directly — force the issue`,tags:['Combat','Direct'],fn(){ resolve('combat','direct assault',enc.tier==='boss'?4:2,'The line breaks under direct force.',`The direct approach costs something.`); if(state.hp<=0&&!state.stage5Dead) handleDeath(); else{setThreat();setObjective();persist();render();} }},
      {label:`Find the weakness and work it precisely`,tags:['Stealth','Precise'],fn(){ resolve('stealth','precision approach',enc.tier==='boss'?3:2,'The weak point opens and the threat unravels.','The precision read fails under pressure.'); if(state.hp<=0&&!state.stage5Dead) handleDeath(); else{setThreat();setObjective();persist();render();} }},
      {label:`Apply knowledge and read the threat structure`,tags:['Lore','Read'],fn(){ resolve('lore','analytical approach',enc.tier==='boss'?3:2,'The threat logic becomes legible and the answer follows.','The analytical read produces theory without enough time.'); if(state.hp<=0&&!state.stage5Dead) handleDeath(); else{setThreat();setObjective();persist();render();} }},
      {label:`Withdraw and regroup at the safe zone`,tags:['Retreat','Safe'],fn(){ state.encounter=null; advanceTime(1); state.hp=Math.max(1,state.hp); state.lastResult=`The threat is left behind. The safe zone holds for now.`; setThreat();setObjective();persist();render(); }}
    ];
    return choices;
  }

  function stage3to5Choices(stage){ const arr=objectiveWebChoices(stage).slice(0,5); if(stage===5 && G.finalBreak){ arr.push({label:'Commit to the final boss confrontation',tags:['Boss','Final'],fn(){ beginEncounter(G,'creature',G.currentThreat.creature,'boss'); }}); arr.push({label:'Commit to the final hazard confrontation',tags:['Boss','Final'],fn(){ beginEncounter(G,'hazard',G.currentThreat.hazard,'boss'); }}); } else { arr.push({label:'Force an elite confrontation now',tags:['Encounter','Elite'],fn(){ startThreatEncounter('elite'); }}); } arr.push({label:'Camp and re-form the line',tags:['Camp'],fn(){ G.lastResult='The camp settles nerves but the wider pressure does not stop moving.'; }}); return arr.slice(0,8); }
  function maybeStageAdvance(){ if(G.stage===1 && G.stageProgress[1]>=4 && G.level>=5){ G.stage=2; updateStage(); addNotice('Stage II begins. Adjacent pressure opens.'); markMoment('Stage II began'); } if(G.stage===2 && G.stageProgress[2]>=4 && G.level>=9){ G.stage=3; updateStage(); addNotice('Stage III begins. The world grows wider and less forgiving.'); markMoment('Stage III began'); } if(G.stage===3 && G.familyMilestones.stage3>=3 && G.level>=13){ G.stage=4; updateStage(); addNotice('Stage IV begins. Your name now changes what institutions dare.'); markMoment('Stage IV began'); } if(G.stage===4 && G.familyMilestones.stage4>=3 && G.level>=17){ G.stage=5; updateStage(); addNotice('Stage V begins. Death is now final.'); markMoment('Stage V began'); } setObjective(); }
  function currentChoices(){ if(G.encounter) return encounterChoices(G); if(G.stage===1) return stage1Choices(); if(G.stage===2) return stage2Choices(); if(G.stage===3) return stage3to5Choices(3); if(G.stage===4) return stage3to5Choices(4); return stage3to5Choices(5); }
  function startThreatEncounter(tier){ const threat=G.currentThreat||chooseThreat(); if(!threat) return; const kind=rand(2)===0?'creature':'hazard'; const name=kind==='creature'?threat.creature:threat.hazard; G.telemetry.encounters++; beginEncounter(G,kind,name,tier||'standard'); }
  function handleDeath(){ G.deathCount+=1; if(G.stage===5){ G.stage5Dead=true; G.lastResult='The final line breaks. This run ends here.'; saveLegend('Permadeath'); persist(); render(); return; } const oldLoc=getLocality(G.location); const rescue=(window.RESCUE_PROFILES||{})[G.location]||{rescuer:'unrecorded rescuers',aftermath:'The cost is real even if the names are not.',safeZone:oldLoc.safeZone}; const next=((window.ADJACENCY[G.location]||[])[0]) || G.location; const nextLoc=getLocality(next); G.location=next; G.currentSafeZone=rescue.safeZone || nextLoc.safeZone; G.safeZoneHistory.unshift(`${G.currentSafeZone} (${nextLoc.name})`); G.safeZoneHistory=G.safeZoneHistory.slice(0,10); G.hp=Math.max(6,Math.floor(G.maxHp*0.4)); G.fatigue+=2; G.gold=Math.max(0,G.gold-3); G.wounds.push(`Near-death at ${oldLoc.name}`); G.wounds=G.wounds.slice(0,6); G.worldClocks.rival+=2; G.worldClocks.pressure+=1; G.telemetry.rescues++; G.companions.forEach(c=>{ if(rand(4)===0){ c.injured=true; c.available=false; c.trust=Math.max(0,(c.trust||1)-1); } }); G.rescueLog.unshift(`Recovered near ${oldLoc.name} by ${rescue.rescuer}; carried to ${G.currentSafeZone}. ${rescue.aftermath}`); G.rescueLog=G.rescueLog.slice(0,10); G.lastResult=`${oldLoc.name} is lost for now. ${rescue.rescuer[0].toUpperCase()+rescue.rescuer.slice(1)} bring the party to ${G.currentSafeZone}. ${rescue.aftermath}`; markMoment(`Rescued after near-death at ${oldLoc.name}`); setThreat(); setObjective(); }
  function saveLegend(finalOutcome){ const bg=getBackground(G.archetype,G.backgroundId); const arch=getArchetype(G.archetype); const loc=getLocality(routeSignature().originLocality); G.legends.unshift({name:G.name, archetypeName:arch.name, backgroundName:bg.name, originLocalityName:loc.name, lifeOverview:G.lifeOverview, keyMoments:[...G.keyMoments], safeZones:[...G.safeZoneHistory], finalOutcome, stage5Dead:G.stage5Dead, familyEdges:[...(G.familyEdges||[])], rescueLog:[...G.rescueLog], routeScoutLog:[...G.routeScoutLog], companions:G.companions.map(c=>c.name), dayCount:G.dayCount, level:G.level}); G.legends=G.legends.slice(0,20); }
  function legendLines(){ return G.legends.map((l,i)=>`<div class='card'><b>${i+1}. ${l.name}</b><div>${legendSummary(l)}</div></div>`).join('')||'<div class="card">No legends recorded yet.</div>'; }
  function journalLines(){ return G.journalRecords.map(r=>`<div class='card'><b>${r.category}</b><div>Day ${r.day} · ${getLocality(r.locality)?.name||r.locality}</div><div>${r.text}</div></div>`).join('')||'<div class="card">No journal records yet.</div>'; }
  function noticesLines(){ const noticeHtml = G.notices.map(n=>`<div class='card'>${n}</div>`).join(''); return `<div class='notice-list'>${noticeHtml||'<div class="card">No notices yet.</div>'}</div>`; }
  function npcsLines(){ return currentNamedPlacements(G.location).map(n=>`<div class='card'><b>${n.id.replace(/_/g,' ')}</b><div>${n.role} · ${n.office}</div></div>`).join('')||'<div class="card">No named placements surfaced here yet.</div>'; }
  function campLines(){ return campChoices(G).map((c,i)=>`<button class='choice small' data-camp='${i}'>${c.label}</button>`).join(''); }
  function mapLines(){ const sig=routeSignature(); const atlas=routeAtlasFor(sig); const fam=familyTitleForStage2(sig); const top=`<div class='card'><div class='sectionTitle'>Current Vector</div><b>${window.ROUTE_NAMES[sig.stage2Vector]}</b><div>${atlas.style}</div><div>Risk: ${atlas.risk}</div><div>${atlas.note}</div><div><span class='muted'>Family:</span> ${fam}</div></div>`; const adj=(window.ADJACENCY[G.location]||[]).map(dest=>{ const dl=getLocality(dest); const seen=G.stage2DestinationsSeen[dest]?'Seen':'Unseen'; const preview=destinationStage2Content(dest)[0]; return `<div class='card'><b>${dl.name}</b><div>${dl.summary}</div><div><span class='muted'>Status:</span> ${seen}</div><div><span class='muted'>Pressure:</span> ${preview?preview.label:'Adjacent pressure not yet surfaced.'}</div></div>`; }).join(''); return top+(adj||'<div class="card">No adjacent routes surfaced here yet.</div>'); }
  function poiActions(){ const locPois=(window.SETTLEMENT_POIS||{})[G.location]||{}; const group=getArchetype(G.archetype).group; const basePool=(window.SERVICE_ITEM_POOLS||{})[group]||[]; const localPool=((window.LOCALITY_SERVICE_ITEM_OVERRIDES||{})[G.location]||{})[group]||[]; const itemPool=[...localPool,...basePool]; return Object.entries(locPois).map(([key,poi])=>({key,poi,itemPool,action:()=>{ advanceTime(1); G.telemetry.turns++; G.telemetry.services++; if(key==='recovery'){ G.hp=Math.min(G.maxHp,G.hp+5); G.fatigue=Math.max(0,G.fatigue-2); G.lastResult=`${poi.name} steadies the body and lowers immediate strain.`; }
      else if(key==='equipment'){ const item=itemPool[(G.dayCount+G.level)%itemPool.length]; if(G.gold>=item.cost){ G.gold-=item.cost; G.inventory.unshift(item); G.inventory=G.inventory.slice(0,30); G.equipment[item.slot]=item; G.lastResult=`${poi.name} equips ${item.name}. ${item.text}`; } else G.lastResult=`${poi.name} offers what would help, but not at the coin currently on hand.`; }
      else if(key==='info'){ gainXp(1,'settlement information'); addJournal('information', `${poi.name}: ${poi.text}`, `${G.location}-${key}-${G.dayCount}`); G.lastResult=`${poi.name} turns rumor into something more actionable.`; }
      else if(key==='progression'){ const focus=getArchetype(G.archetype).focus; G.skills[focus]=(G.skills[focus]||0)+1; gainXp(1,'local progression'); G.lastResult=`${poi.name} sharpens ${focus} into a more reliable edge.`; }
      else if(key==='flavor'){ G.renown+=1; addJournal('locality', `${poi.name}: ${poi.text}`, `${G.location}-${key}`); G.lastResult=`${poi.name} makes the place feel fully inhabited and harder to mistake for anywhere else.`; }
      else if(key==='secret'){ G.settlementSecrets[G.location]=true; G.gold+=3; addJournal('secret', `${poi.name}: ${poi.text}`, `${G.location}-secret`); G.lastResult=`${poi.name} yields a hidden leverage point and a small practical gain.`; }
      G.serviceLog.unshift(`${poi.name} (${key}) at ${getLocality(G.location).name}`); G.serviceLog=G.serviceLog.slice(0,20); setThreat(); persist(); render(); }})); }
  function servicesLines(){ return poiActions().map((p,i)=>{ const stock = p.key==='equipment' && p.itemPool.length ? `<div><span class='muted'>Stock:</span> ${p.itemPool.slice(0,2).map(x=>x.name).join(', ')}</div>` : ''; return `<div class='card'><div class='sectionTitle'>${p.key}</div><b>${p.poi.name}</b><div>${p.poi.text}</div>${stock}<button class='choice small' data-service='${i}'>Use ${p.poi.name}</button></div>`; }).join('') || '<div class="card">No meaningful services surfaced here yet.</div>'; }
  function sheetLines(){ const arch=getArchetype(G.archetype), bg=getBackground(G.archetype,G.backgroundId); updateSignals(); const inv=(G.inventory||[]).slice(0,6).map(i=>i.name).join(', ')||'None'; const eq=Object.entries(G.equipment||{}).map(([slot,item])=>`${slot}: ${item.name}`).join(' · ')||'None'; return `<div class='card'><div class='sectionTitle'>Identity</div><b>${arch.name}</b> · ${bg.name}<br>${G.stageLabel}<br>${buildAuditText()}<br>${G.lifeOverview}</div><div class='card'><div class='sectionTitle'>State</div>Objective: ${G.currentObjective}<br>Companions: ${G.companions.map(c=>c.name).join(', ') || 'None'}<br>Family edges: ${familyEdgesText()}<br>Stage II destinations seen: ${Object.keys(G.stage2DestinationsSeen||{}).length}<br>Rescues: ${G.rescueLog.length} · Legends: ${G.legends.length}<br>Telemetry: ${G.telemetry.actions} actions · ${G.telemetry.encounters} encounters · ${G.telemetry.services} services</div><div class='card'><div class='sectionTitle'>Readiness</div>${Object.values(G.signals||{}).join(' · ')}</div><div class='card'><div class='sectionTitle'>Equipment</div>${eq}<br><span class='muted'>Inventory:</span> ${inv}</div>`; }
  function renderChoices(){ const list=currentChoices(); $('choices').innerHTML=list.map((c,i)=>`<button class='choice' data-choice='${i}'><span>${c.label}</span><small>${(c.tags||[]).join(' · ')}</small></button>`).join(''); [...document.querySelectorAll('[data-choice]')].forEach(btn=>btn.onclick=()=>{ const c=list[+btn.dataset.choice]; c.fn(); if(G.hp<=0 && !G.stage5Dead) handleDeath(); setThreat(); setObjective(); persist(); render(); }); }
  function render(){ updateStage(); setObjective(); updateSignals(); const sig=routeSignature(); const atlas=routeAtlasFor(sig); $('title').textContent=`Ledger of Ash — Upgrade Batch 27`; $('header').textContent=`${getLocality(G.location).name} · Day ${G.dayCount} · ${['Dawn','Morning','Midday','Late Day','Night'][G.timeIndex]} · Level ${G.level}`; $('stats').textContent=`${getArchetype(G.archetype).name} · ${getBackground(G.archetype,G.backgroundId).name} · HP ${G.hp}/${G.maxHp} · Renown ${G.renown} · Gold ${G.gold}`; $('narrative').textContent=localityNarrative(G,getLocality(G.location),{pressure:pick(getLocality(G.location).pressures,G.worldClocks.pressure),routeHint:window.ROUTE_NAMES[sig.stage2Vector],routeStyle:atlas.style,routeRisk:atlas.risk,hazardHint:G.currentThreat?.hazard,creatureHint:G.currentThreat?.creature,namedHint:currentNamedPlacements(G.location).map(n=>`${n.id.replace(/_/g,' ')} at ${n.office}`).join('; '), serviceHint:(G.serviceLog[0]||''), familyHint:familyTitleForStage2(sig), destinationHint:Object.keys(G.stage2DestinationsSeen||{}).length?`The widening route now carries remembered names like ${Object.keys(G.stage2DestinationsSeen).slice(0,2).map(id=>getLocality(id).name).join(' and ')}.`:''}); $('result').textContent=resultNarrative(G.lastResult); $('mapPanel').innerHTML=mapLines(); $('servicesPanel').innerHTML=servicesLines(); $('sheetPanel').innerHTML=sheetLines(); $('journalPanel').innerHTML=journalLines(); $('noticesPanel').innerHTML=noticesLines(); $('npcsPanel').innerHTML=npcsLines(); $('campPanel').innerHTML=campLines(); $('legendsPanel').innerHTML=legendLines(); renderChoices(); [...document.querySelectorAll('[data-camp]')].forEach(btn=>btn.onclick=()=>{ const choice=campChoices(G)[+btn.dataset.camp]; choice.fn(); persist(); render(); }); [...document.querySelectorAll('[data-service]')].forEach(btn=>btn.onclick=()=>{ const action=poiActions()[+btn.dataset.service]; action.action(); }); }
  function fillSelectors(){ const archSel=$('archSelect'); archSel.innerHTML=window.ARCHETYPES.map(a=>`<option value='${a.id}'>${a.name}</option>`).join(''); $('ageSelect').innerHTML=['18','21','24','28','34','41','53'].map(v=>`<option value='${v}'>Age ${v}</option>`).join(''); $('presentationSelect').innerHTML=['Male','Female','Non-Gendered'].map(v=>`<option value='${v}'>${v}</option>`).join(''); function fillBg(){ const ids=window.BACKGROUNDS[archSel.value]||[]; $('bgSelect').innerHTML=ids.map(b=>`<option value='${b.id}'>${b.name} — ${getLocality(b.originLocality).name}</option>`).join(''); } archSel.onchange=fillBg; fillBg(); }
  function beginNew(){ G=defaultState(); G.name=$('newName').value.trim()||'Nameless'; G.passcode=$('newCode').value.trim() || ('0000'+rand(10000)).slice(-4); G.archetype=$('archSelect').value; G.backgroundId=$('bgSelect').value; G.age=$('ageSelect').value; G.presentation=$('presentationSelect').value; const arch=getArchetype(G.archetype); const bg=getBackground(G.archetype,G.backgroundId); G.location=bg.originLocality; const lineages=(window.LOCALITY_LINEAGES||{})[G.location] || ['Human']; G.lineage=lineages[0]; G.currentSafeZone=bg.firstSafeZone; G.safeZoneHistory=[bg.firstSafeZone]; G.maxHp=20 + (arch.group==='combat'?4:arch.group==='support'?2:0); G.hp=G.maxHp; G.skills[arch.focus]=(G.skills[arch.focus]||0)+1; (window.STARTING_LOADOUT_BY_GROUP[arch.group]||[]).forEach((name,idx)=>G.inventory.push({name,slot:['weapon','kit','belt'][idx]||'kit',bonus:{}})); G.lifeOverview=window.lifeOverviewText?lifeOverviewText(G):`${G.name} starts in ${getLocality(G.location).name}.`; addQuest('stage1', bg.firstObjective, 'Active'); setThreat(); setObjective(); persist(); render(); }
  function loadLegend(){ const code=$('loadCode').value.trim(); const all=storage(); const found=all[code]; if(!found){ alert('Legend not found.'); return; } G=found; if(!G.familyEdges) G.familyEdges=[]; if(!G.telemetry) G.telemetry={turns:0,actions:0,travels:0,scouts:0,encounters:0,wins:0,rescues:0,services:0}; if(!G.inventory) G.inventory=[]; if(!G.equipment) G.equipment={}; if(!G.serviceLog) G.serviceLog=[]; render(); }
  window.addEventListener('DOMContentLoaded',()=>{ fillSelectors(); $('beginBtn').onclick=beginNew; $('loadBtn').onclick=loadLegend; G=defaultState(); G.lifeOverview='Create a new legend to enter the world.'; setThreat(); render(); });
})();
