window.LOCALITY_NARRATIONS = {

  shelkopolis: 'The city does not announce itself gently. Even from the road, the smell arrives first — coal smoke and old stone, fish salt from the harbor district, the sharp chemical note of the tanneries downwind. The streets inside the gate are narrow and purposeful, buildings leaning close as if in conference. A crier reads notices from a post outside the Iron Accord registry. Nearby, a woman in House Mimolot colors argues with a cart driver about something to do with permits. Two children race across the mouth of an alley without looking. The city is indifferent to your arrival and deeply, mechanically alive.',

  panim_haven: 'The fishing village smells of drying nets and the particular rot of things the sea discards. The docks are small, practical, patched. A weathered notice board outside the harbormaster\'s shed lists tide times and missing persons in the same bureaucratic hand. Gulls argue over something in the water. The main street has four businesses: a tavern, a chandler, a bait seller, and a building with no sign whose purpose you cannot immediately determine. An old man on a dock bench watches the horizon with the expression of someone who has given up expecting it to be interesting.',

  cosmoria: 'The harbor district is built on two levels: the working docks below, slick with brine and cargo chains, and the commercial street above, where the ledger-keepers and factors watch the cranes from behind counting-house windows. The smell is salt and grain and something slightly off — weevils in the storage, perhaps, or something heavier in the water. A stevedore argues with a foreman about weight records. The foreman has a ledger. The stevedore does not. The foreman wins.',

  fairhaven: 'The mill town is quieter than a working mill town should be. The wheel turns, the grind continues, but the workers move through it with the particular silence of people who have stopped talking to each other about something important. The main square has a well, a notice board, and three benches where nobody is sitting. A woman hangs laundry from a window above a shuttered shopfront. She looks down once, then away. The mill road has cart-ruts from the morning run. The afternoon run has not come.',

  guildheart_hub: 'The hub is a transit town that has mistaken itself for an administrative center. The main avenue has a genuine customs house, a surveyor\'s office, and a building that houses three competing guilds in separate wings — the wall between the Artificers and the Handlers is load-bearing in a way that suggests it was not always there. Carts move through in both directions. Clerks argue about manifest formats under a covered walkway. Someone is always in the middle of something and nobody is finished with it.',

  soreheim_proper: 'The city is built for extraction and management, not for aesthetics. The quota offices occupy the most prominent street, their façades marked with production tallies from the current season. The Giant administrators move through the population with the ease of people who have never needed to explain their authority. A row of standardized workers\' housing lines the eastern approach. The ration-distribution point near the central market has a queue that has clearly been there since morning. The scale of everything is calibrated for efficiency — functional, correct, and precisely as comfortable as required.',

  aurora_crown_commune: 'The commune is older than its current governance. The buildings are stone and earth-brick, built over generations, walls thick enough to lean into. Every communal space has a message-board — not announcements, but records, names, decisions, the accumulated living memory of a shared administration. The grain stores are communal, clearly labeled, maintained. A child plays near the registry hall while two elders revise something at a table near the door. The sounds are domestic: cooking, someone hammering, the low register of a discussion in the next building.',

  glasswake_commune: 'The commune sits on a shallow estuary, its buildings on stilts above the seasonal flood line. The water carries light strangely here — the surface breaks reflections into fragments that suggest shapes that are not there. The dock planks are salt-bleached and replace-marked; everything here gets replaced eventually. A fisherman mends a net on the shore. He does not look up when you arrive.',

  whitebridge_commune: 'The bridge is older than the commune. The commune grew around it, organized itself by it, named itself after it. The stone is white-grey and cold to the touch even in summer. The commune buildings cluster on both banks in a way that makes the bridge the center of everything — market, meeting, transit, argument. Two people stand at the rail mid-bridge looking at the water below. They are not talking to each other.',

  ironhold_quarry: 'The quarry has been working this site for over a century — you can tell by the way the stone face has retreated into the hillside, methodically, in horizontal bands. The workers are quiet in the way that people who work near loud machinery always are, voices tuned to carry over distance. A foreman marks a tally board near the equipment shed. The dust is everywhere, coating the roadside brush in white grey.',

  plumes_end_outpost: 'The outpost is a relay and a waypoint and not much else. Two buildings, a supply cache, a well, and a fire-signal platform that has not been used in years. The Roadwarden on duty is reading something. She does not put it down when you arrive. The track east is less maintained than the track you came in on.',

  craftspire: 'The spire is not a natural formation — it is a building, or was once, or is something in between. The structure rises higher than it has any right to from this size of settlement, its upper reaches modified and remodified over centuries. The artificers\' workshops cluster at its base. The smell is hot metal and flux. A queue outside the guild registry suggests the spire\'s reputation extends beyond its walls.',

  unity_square: 'The square was built to be ceremonial and has become commercial through sheer civic inertia. The stage at the center is used for trade announcements and labor allocation, not speeches. Factors walk the perimeter taking notes. A public ledger near the entrance records work assignments for the current week. The inscription above the gate, partially obscured by a posted notice, reads something about solidarity. The notice is about cart-load fees.',

  shelkopolis_harbor: 'The harbor is a separate city from the streets above it. Down here, the scale changes: crane-arms over the water, warehouses the size of civic buildings, the constant creak and complaint of ships at load. The customs house operates at all hours with the grim efficiency of an institution that cannot afford delays. A Collegium inspector makes notes on a clipboard near berth seven. Two dockhands watch him from across the pier without speaking.',

  guildheart_archive: 'The archive annex is attached to the hub\'s administrative building by a covered walkway that always seems to be in shadow. The reading room smells of paper and preservation wax. A single archivist manages intake and reference from a desk surrounded by indexed containers. The shelves go further back than the building\'s exterior suggests they should.',

  mimolot_academy: 'The academy sits above the city on a terraced hillside, its buildings arranged in a way that suggests it was designed to overlook everything. The students move through its paths with the focused distraction of people who are always thinking about something other than where they are walking. The main library is marked by a carved lintel that lists its founding principles in an old script. Someone has pasted a student broadsheet over the bottom half of the inscription.',

  sheresh_coastal_commune: 'The commune sits on the high ground above the tide line, facing the sea. The buildings are organized around the memory hall — the largest structure, kept clean, its records more rigorously maintained than the infrastructure around it. An elder reads from the commune registry to a group of children on the steps. She does not look up when you pass, but she notes the time.',

  soreheim_transit_post: 'The transit post is the administrative midpoint between two quota districts, and it knows it. The manifest clerks work in parallel at long counters. The verification office has a queue. The compliance office does not have a queue, which means it either does very little or very much. A factor in Alliance colors argues with a clerk about load classification while a Roadwarden watches from the corner with the expression of someone who has watched this argument happen before.'

};
