window.LOCALITY_NARRATIONS = {

  shelkopolis: 'The pale stone walls show from the road — indigo and emerald banners at the gatehouse, bright-plumed Roadwardens posted at the approach. The smell arrives before you do: coal smoke and old stone, fish salt from the harbor district, the sharp chemical note of the tanneries downwind. Inside the gate, the streets are narrow and purposeful, buildings leaning close as if in conference. A crier reads notices from a post outside the Iron Accord registry. A woman in House Mimolot colors argues with a cart driver about permits. Two children race across an alley mouth without looking. The city does not register your arrival.',

  panim_haven: 'The approach road runs past funerary markers — small stone tablets in the House Panim custom, names and death dates carved without epitaphs. The harbor is here, and the fishing goes on, but the dominant economy is ritual: shrines occupy three of the main street\'s visible buildings, and the fourth handles funerary logistics, its doors open to a courtyard where offerings are sorted by type. A shrine intermediary moves through the dock traffic with a ledger. The tide times and the ritual calendar share the notice board outside the harbormaster\'s shed. The smell is incense and salt and the particular cold of things the sea discards.',

  cosmoria: 'The harbor district is built on two levels: the working docks below, slick with brine and cargo chains, and the commercial street above, where the ledger-keepers and factors watch the cranes from behind counting-house windows. The great library backs against the upper street — its doors are open but its reading rooms require a valid trader\'s certificate to enter. The smell is salt and grain and something slightly off, weevils in the storage perhaps, or something heavier in the water. A stevedore argues with a foreman about weight records. The foreman has a ledger. The stevedore does not. The foreman wins.',

  fairhaven: 'The access roads come from three directions: the east track from the plain, the mill road, and the cave approach from below Watcher\'s Perch, which brings a different kind of traveler — dust on their boots, the quiet of people who have come out of the dark. The mill town is quieter than a working mill town should be. The wheel turns, the grind continues, but the workers move through it with the particular silence of people who have stopped talking to each other about something important. The main square has a well, a notice board, and three benches where nobody is sitting. The afternoon cart run has not come.',

  guildheart_hub: 'The hub reads as transit on most manifests, but it has accumulated authority it did not plan for. Multi-story counting halls face the main avenue. Bonded warehouse blocks line the canal-side loading lanes. Registry towers mark the four corners of the administrative district. Two competing guilds share a building whose partition wall is load-bearing — the seam in the plaster still shows. Carts move through in both directions. Clerks argue about manifest formats under a covered walkway. Someone is always in the middle of something and nobody is finished with it.',

  soreheim_proper: 'The Titan Towers are visible from the approach road — four of them, colossal, rising from volcanic hillside above the industrial district, their upper levels lost in heat haze from the extraction works below. The quota offices occupy the most prominent street, their façades marked with production tallies from the current season. A Giant administrator moves through the market without altering her pace for the people in her path. They move. A row of standardized workers\' housing lines the eastern approach. The ration-distribution point near the central market has a queue that has been there since morning. The air smells of sulfur and wet ash.',

  aurora_crown_commune: 'The commune is built inside a dome — blue-white light from the reinforced panels, layered ice walls visible through the outer access corridor, guarded thermal inlets along the floor of the main passage. Everything is maintained with the discipline of people who cannot afford infrastructure failure. The communal spaces have message boards: not announcements, but records, names, decisions, the accumulated living memory of shared administration. A warden stands at the dome junction with a monitoring instrument. Two elders revise something at a table near the registry hall. The sounds are domestic: cooking, someone hammering, the low register of a discussion in the next building.',

  glasswake_commune: 'The reinforced dome is the first thing visible from the approach — low, grey-white, surrounded by sensor pylons and flagged exposure trenches. The estuary is here, and the stilts, but the monitoring infrastructure dominates: instrument stations on the shore, color-coded exposure markers on every post. A fisherman mends a net at the approved shoreline. A warden checks instrument readings near the northern trench. The water carries light strangely, surface breaking reflections into shapes that are not there. Everything here gets replaced eventually — the replace-marks are on the dock planks, the pylons, the flaglines.',

  whitebridge_commune: 'The stone is white-grey and cold to the touch even in summer — the bridge holds the temperature of whatever runs below it. Signal braziers stand at both ends, unlit, their iron grates dusted with last night\'s frost. Snow-buried storage ribs are visible behind the eastern buildings. The commune organized itself around the bridge: market, meeting, transit, argument all route through it. Two people stand at the rail mid-bridge looking at the water below. They are not talking to each other.',

  ironhold_quarry: 'The quarry has been working this site for over a century — the stone face has retreated into the hillside in horizontal bands, methodical and legible. Workers move in designated lanes between the extraction face and the equipment shed. A marshal with a tally board stands at the transport junction; the count goes on a second board near the gate. The dust is everywhere, coating the roadside brush in white-grey. The workers are quiet in the way of people who work near loud machinery, and also in the way of people who have learned that talking draws attention.',

  plumes_end_outpost: 'The outpost is a relay and waypoint: a tavern, an armory, a supply waystation, and a shrine to whoever is owed safe passage here — all four buildings arranged around a well inside a low stockade wall. The Roadwarden on duty is reading something. She does not put it down when you arrive. The fire-signal platform above the stockade has not been used in years; the flag rope is coiled and tied. The track east is less maintained than the track you came in on.',

  craftspire: 'The spire is not a natural formation — modified and remodified over centuries, its upper reaches rising beyond any structural logic from a settlement this size. Around its base: workhouses with ledger balconies facing the street, a copy tower near the guild registry entrance, materials yards stacked with raw stock labeled by grade. Cart-choked service lanes run between the buildings. The smell is hot metal and flux. A queue outside the guild registry suggests the spire\'s reputation extends further than its walls.',

  unity_square: 'The square was built to be ceremonial. What it is now is a civic market machine. Paved exchange courts fill the center. Color-coded guild awnings line the perimeter — each faction\'s territory marked and maintained. A tally tower near the main entrance posts current load fees and labor allocations. The stage at the center is used for trade announcements, not speeches. Factors walk the perimeter taking notes. The inscription above the gate, partially obscured by a posted notice, reads something about solidarity. The notice is about cart-load fees.',

  shelkopolis_harbor: 'The harbor is a separate city from the streets above it. Down here, the scale changes: crane-arms over the water, warehouses the size of civic buildings, the constant creak and complaint of ships at load. The customs house operates at all hours with the grim efficiency of an institution that cannot afford delays. A Collegium inspector makes notes on a clipboard near berth seven. Two dockhands watch him from across the pier without speaking.',

  guildheart_archive: 'The archive annex is attached to the hub\'s administrative building by a covered walkway that always seems to be in shadow. The reading room smells of paper and preservation wax. A single archivist manages intake and reference from a desk surrounded by indexed containers. The shelves go further back than the building\'s exterior suggests they should.',

  mimolot_academy: 'The academy sits above the city on a terraced hillside, its buildings arranged to overlook everything. The outer wall has a registration checkpoint inside the gate — academic business only, staffed, a warden in Mimolot colors keeping a separate log. The main library\'s carved lintel lists its founding principles in an old script; someone has pasted a student broadsheet over the bottom half. Students move through the paths without looking up. Wards mark the archive doors with House Mimolot seals. A monitoring station near the upper archive runs instruments that do not display what they are recording.',

  sheresh_coastal_commune: 'The commune sits inside a reinforced seawall — not Collegium-built, older, maintained by rotation. The salt air inside is trapped and slightly stale. The buildings are organized around the memory hall, the largest structure, kept clean, its records more rigorously maintained than the infrastructure around it. An elder reads from the commune registry to a group of children on the steps. She does not look up when you pass, but she notes the time.',

  soreheim_transit_post: 'The transit post sits at the administrative midpoint between two quota districts. The manifest clerks work in parallel at long counters. The verification office has a queue. The compliance office does not have a queue, which means it either does very little or very much. A factor in Alliance colors argues with a clerk about load classification while a Roadwarden watches from the corner with the expression of someone who has watched this argument happen before.'

};
